version: "3.7"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/plex/certs:/etc/nginx/certs
    networks:
      plex_stack:
        ipv4_address: 10.0.0.15

  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VIRTUAL_HOST=grocy.${DOMAIN}
      - VIRTUAL_PORT=80
    volumes:
      - ${DOCKER_CONFIGS}/grocy:/config
    restart: unless-stopped
    networks:
      plex_stack:
        ipv4_address: 10.0.0.24

  organizr:
    container_name: organizr
    image: organizr/organizr
    restart: unless-stopped
    ports:
      - 9090:80/tcp
    environment:
      - fpm=true
      - branch=v2-master
      - VIRTUAL_HOST=organizr.${DOMAIN}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/organizr-v2:/config
    networks:
      plex_stack:
        ipv4_address: 10.0.0.10

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989/tcp
    environment:
      VIRTUAL_HOST: sonarr.${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/sonarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_LIB}:/tv
    networks:
      plex_stack:
        ipv4_address: 10.0.0.4

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    environment:
      VIRTUAL_HOST: radarr.${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/radarr:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIE_LIB}:/movies
    networks:
      plex_stack:
        ipv4_address: 10.0.0.5

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=#{TZ}
      - VIRTUAL_HOST=lidarr.${DOMAIN}
    volumes:
      - ${DOCKER_CONFIGS}/lidarr:/config
      - ${MUSIC_LIB}:/music #optional
      - ${DOWNLOAD_DIR}:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      plex_stack:
        ipv4_address: 10.0.0.14

  jackett:
    container_name: jackett
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: jackett.${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/jackett:/config
      - ${DOWNLOAD_DIR}:/downloads
    network_mode: service:expressvpn
    depends_on:
           - expressvpn

  ombi:
    container_name: ombi
    image: lscr.io/linuxserver/ombi:latest
    restart: unless-stopped
    ports:
      - 3579:3579/tcp
    environment:
      VIRTUAL_HOST: ombi.${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/ombi:/config
    networks:
      plex_stack:
        ipv4_address: 10.0.0.7


  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    restart: unless-stopped
    ports:
      - 8181:8181/tcp
    environment:
      VIRTUAL_HOST: tautulli.${DOMAIN}
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${DOCKER_CONFIGS}/tautulli:/config
      - ${DOCKER_CONFIGS}/plex/Library/Application Support/Plex Media Server/Logs:/logs
    networks:
      plex_stack:
        ipv4_address: 10.0.0.9


  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    volumes:
      - ${DOCKER_CONFIGS}/plex:/config
      - ${TRANSCODE_DIR}:/transcode
      - ${MOVIE_LIB}:/data/movies
      - ${TV_LIB}:/data/tv
      - ${MUSIC_LIB}:/data/music
      - ${LIB_DIR}/prerolls:/data/prerolls
        #      - ${LIB_DIR}:/data
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      VIRTUAL_HOST: plex.${DOMAIN}
      PLEX_CLAIM: ${PLEX_CLAIM}
      TZ: ${TZ}
    privileged: true
    network_mode: host
    devices:
      - /dev/dri:/dev/dri

  expressvpn:
    container_name: expressvpn
    image: polkaned/expressvpn
    environment:
      - ACTIVATION_CODE=${VPN_ACTIVATIONCODE}
      - SERVER=${VPN_SERVER}
      - PREFERRED_PROTOCOL=${VPN_PROTOCOL}
      - LIGHTWAY_CIPHER=${VPN_CIPHER}
      - VIRTUAL_HOST=qbittorrent.${DOMAIN},jackett.${DOMAIN}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
    command: /bin/bash
    privileged: true
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 9117:9117

  qbittorrent-expressvpn:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      WEBUI_PORT: 8080
    volumes:
      - ${DOCKER_CONFIGS}/qbittorrent:/config
      - ${DOWNLOAD_DIR}:/downloads
    network_mode: service:expressvpn
    depends_on:
      - expressvpn
    restart: unless-stopped


networks:
  plex_stack:
    driver: bridge
    ipam:
     config:
      - subnet: 10.0.0.0/24